version: "3.9"
services:
  db:
    image: postgres:latest
    env_file:
      - env/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  web:
    build: .
    depends_on:
      - db
    env_file:
      - env/postgres.env
      - env/django.env
    volumes:
      - static-data:/var/website/static
      - ./website:/usr/src/website
    links:
      - db:database

  nginx:
    image: nginx:latest
    depends_on:
      - web
    env_file:
      - env/nginx.env
    ports:
      - "80:80"
    volumes:
      - static-data:/var/website/static:ro
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - web:web

volumes:
  postgres-data:
  static-data:
