version: "3.9"
services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    depends_on:
      - db
    env_file: .env
    volumes:
      - static_data:/var/website/static
      - ./website:/usr/src/website

  nginx:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_data:/var/website/static:ro
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - web:web

volumes:
  postgres_data:
  static_data:
