# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Django Docker Template
site_url: https://github.com/amerkurev/django-docker-template  # TODO: replace to django-docker.dev

repo_url: https://github.com/amerkurev/django-docker-template
repo_name: django-docker-template

edit_uri: edit/master/

theme:
  name: material
  # https://icon-sets.iconify.design/?query=django
  logo: images/logo.svg
  favicon: images/favicon.svg
  features:
    - toc.integrate
    - content.code.copy
    - content.code.annotate
#    - navigation.instant
#    - navigation.instant.progress
#    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.edit
#    - content.action.view
    - content.tabs.link
    - content.tooltips
    - navigation.top
    # - navigation.expand
    # - navigation.tracking
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#system-preference
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

# noinspection YAMLSchemaValidation
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite

# noinspection YAMLSchemaValidation
plugins:
  - search

extra_css:
  - stylesheets/extra.css
